### ISSUE TITLE
abrt-applet tray icon missing

### ISSUE THREAD

**Issue by drorriss** [abrt/abrt#1085]
abrt-applet used to produce a tray icon (when a crash occurs) back in Fedora 20 and prior; when I upgraded to Fedora 22, the tray icon no longer appeared. This is a problem because I may not be at my computer when the notification bubble appears, so may be unaware that there was a crash when I return to my computer.

Is there a way to re-enable the tray icon? Was it removed? Or is it a bug that it is not appearing?

btw, I'm using the Mate Desktop environment.

**Comment by jfilak** [comment]
The major desktop players have dropped XEmbed support, so the old school systray icon has stopped working. We need to port abrt-applet, the thing that shows the icon, to the new notification models.

**Comment by ernestask** [comment]
> We need to port abrt-applet, the thing that shows the icon, to the new notification models.

I wonder what the new models are, since the applet has been using libnotify since 2009. `GNotification`? I have a working port (which also required porting to `GApplication`), but there’s not much of a difference, other than no longer using a less-than-maintained library, as the fdo spec support is still there, so it should play just as nicely with the myriad servers out there.

GTK+ no longer supports tray icons, meaning that notifications are indeed the way to go. Being away from keyboard should not be an issue if the shell/notification server of your choice does not disappear the notifications themselves.
