### ISSUE TITLE
abrt-cli - order by username and password fields

### ISSUE THREAD

**Issue by mantis** [abrt/abrt#1231]
When reporting issues with abrt-cli, the password/username fields are displayed in an unusual order (and inconsistent order). This occurs on CentoOS

When first requested, the password is requested before the username as shown below
![image](https://cloud.githubusercontent.com/assets/16276382/23831676/60d3325e-071e-11e7-9d1b-3c1576200c78.png)

If you enter an incorrect password, the order is then flipped:

![image](https://cloud.githubusercontent.com/assets/16276382/23831690/93ffbc38-071e-11e7-92c8-a343399d9bca.png)

**Comment by jfilak** [comment]
@mhabrnal Why is it ordered like this?

**Comment by mhabrnal** [comment]
@jfilak the issue is here https://github.com/abrt/libreport/blob/master/src/cli/cli-report.c#L417 . 

Function ``validate_event()`` creates hash table containing config options. There is no strict order in such a hash table while we iterate over its content. Hence, in some cases libreport asks for password before than it asks for login name.

@mkutlak is working on the issue.
