### ISSUE TITLE
abrtr should report "invalid backtrace"

### ISSUE THREAD

**Issue by rugk** [abrt/abrt#1277]
Here abrt showed me an error for an invalid backtrace:
![invalid backtrace](https://bugzilla.redhat.com/attachment.cgi?id=1357673)

It is about a really strange crash, I still don't really know what is causing it: https://bugzilla.redhat.com/show_bug.cgi?id=1516466

Apart from the fact that such a thing can be broken anyway, why not continue to report the bug?

I mean:
* abrtr showed this error to me **at the end** of the process, so from an UX perspective this is really bad. I already filled in STR and such stuff, took my time to fill it in and then it just says "Nope, unlucky guy!"
* also, I checked the dir where abrtr saves the files and there nearly 100MB where saved., Okay, not counting the coredump, it were 60kB, but still enough that I would say there is data to diagnose the problem. Is not it? (I later manually attached some of these things to the already linked Bugzilla issue.)
  Even the simply reason ("Xwayland killed by SIGABRT") already helped me to find potential duplicates once I manually looked into it in the dir…

**Comment by rugk** [comment]
Likely related: https://bugzilla.redhat.com/show_bug.cgi?id=1291093

**Comment by rugk** [comment]
Okay, so is that data really soo useless? Could not maybe the devs/maintainers of one package at least opt-in in such reports?

**Comment by jfilak** [comment]
@rugk Well, let's do a small experiment. Please, file a new bugzilla manually with the information ABRT collected and wait for maintainer's response.

ABRT does not do that because since 2009, when ABRT was started, we have received many outraged emails from maintainers asking us to stop filling bug reports withou a good backtrace.

Do not forget that it is so easy to file a new bug with ABRT - just a few clicks. Before ABRT, users had to do all the stuff manually - download debuginfo, collect logs - so they didn't sped time with crashes that were unlikely to get fixed. This has changed since ABRT was created.

**Comment by rugk** [comment]
I already did in https://bugzilla.redhat.com/show_bug.cgi?id=1516466#c8 and for this bad issue I got the first reply.
It ~was~ is a serious issue so I had reported it anyway, before I noticed abrt saved some data somewhere even though it failed to report it automatically. So maybe it is enough if one can find it manually (and it's not possible with one click), but one has to find it.

So maybe just include a link in the error message. "If you want to report it manually, you can see the collected data [in this dir](link to dir)."?

**Comment by jfilak** [comment]
Good! I really appreaciate your approach. I guess, if the bugzilla was filled by ABRT, it would be ignored - around 50% bugzillas filled by ABRT get closed as EOL - because reporters are not responding and backtrace is not enough.  You have provided the maintainer with Steps-to-reproduce and that's wath ABRT users often ignore and what makes ABRT bugzillas hard to fix (so maintainers tend to ignore ABRT bugzilla - and less valuable backtrace makes it even worse).

Good idea. By the way, you can use abrt-cli to report the bug even if the bactrakce is not usable : `abrt-cli report --unsafe`.

**Comment by rugk** [comment]
Hmm… I just tried your command, and it still does not let me report it:

```console
$ abrt-cli report --unsafe /var/spool/abrt/ccpp-2017-12-21-10:56:37.409173-2713
(»report_uReport« erfolgreich abgeschlossen)
Sind Sie damit einverstanden, den Speicherauszug hochzuladen? Möglicherweise sind vertrauliche Daten darin enthalten. Falls Sie mit »Nein« bestätigen, wird eine lokale Stapelüberwachung erstellt - und damit unter Umständen ein große Datenmenge heruntergeladen. [j/N/f/e] J
Servereinstellungen werden abgefragt
Archiv wird zur Übertragung vorbereitet
1,4 MiB hochladen
Übertragung war erfolgreich
Retrace-Vorgang wurde gestartet
Preparing environment for backtrace generation
........
Generating backtrace
Cleaning environment after backtrace generation
Retrace job finished successfully
Auf Bugzilla nach ähnlichen Fehlern suchen
Berichterstellung deaktiviert, da der Backtrace unbrauchbar ist.
Bitte versuchen Sie, debuginfo manuell mit dem Befehl »debuginfo-install xorg-x11-server-Xwayland-1.19.5-1.fc27« zu installieren und versuchen Sie es erneut.
```

**Comment by rugk** [comment]
```console
$ abrt-cli report -v --unsafe /var/spool/abrt/ccpp-2017-12-21-10:56:37.409173-2713
libreport global configuration already loaded
uReport has been already sent: '/var/spool/abrt/ccpp-2017-12-21-10:56:37.409173-2713'
Bug for '/var/spool/abrt/ccpp-2017-12-21-10:56:37.409173-2713' not yet filed. Continuing.
Sind Sie damit einverstanden, den Speicherauszug hochzuladen? Möglicherweise sind vertrauliche Daten darin enthalten. Falls Sie mit »Nein« bestätigen, wird eine lokale Stapelüberwachung erstellt - und damit unter Umständen ein große Datenmenge heruntergeladen. [j/N/f/e] f
Servereinstellungen werden abgefragt
Archiv wird zur Übertragung vorbereitet
Waiting for tar...
Waiting for xz...
Done...
1,4 MiB hochladen
Übertragung war erfolgreich
Retrace-Vorgang wurde gestartet
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Generating backtrace
Retrace job finished successfully
No exploitable data available
Using product "Fedora".
Using product version 27.
Loading settings from '/etc/libreport/plugins/bugzilla.conf'
create private bz ticket: 'NO'
groups: '0x564de0d2d440'
Initializing XML-RPC library
Auf Bugzilla nach ähnlichen Fehlern suchen
There is no bugzilla bug with 'abrt_hash:7b941b119b09afafb5955856d9d397c5c7360df5'
Berichterstellung deaktiviert, da der Backtrace unbrauchbar ist.
Bitte versuchen Sie, debuginfo manuell mit dem Befehl »debuginfo-install xorg-x11-server-Xwayland-1.19.5-1.fc27« zu installieren und versuchen Sie es erneut.
```

**Comment by JoelStienlet** [comment]
Hello everybody!
I just got this same problem in fedora 28, can't report a SIGSEGV in firefox when opening google maps. A segmentation fault in a webbrowser could be a serious issue, so even reporting the meta-information that errors occur could be helpful I guess. It would also help getting statistics about how often the complete reporting process actually succeeds.

**Comment by xsuchy** [comment]
Several things here:
1) unusable report at the end - it is bad from UX, I agree. But we get this data at the very end of the process. Otherwise, the user will have to wait too long without any clue what is happening.
2) report unusable reports - ABRT did that in the past. The response from the community was "STOP". There is no way, that we enable this by default.
3) even when the report fails, the uReport is sent anyway and is visible on retrace.fedoraproject.org/faf/
See
> uReport has been already sent: '/var/spool/abrt/ccpp-2017-12-21-10:56:37.409173-2713'
4) Failure of ` abrt-cli report -v --unsafe` - this is the only valid thing here. But we would need more data on that. If you want to have this resolved, please open it as a separate issue.
