### ISSUE TITLE
Repeat button is not visible on retrace - window doesn't resize down

### ISSUE THREAD

**Issue by abitrolly** [abrt/abrt#1303]
Repeat button in the case of failed retrace is off screen limits, and impossible to reach as window doesn't resize down vertically.

![image](https://user-images.githubusercontent.com/8781107/39455255-3538daf2-4ce8-11e8-8403-0161919b67f2.png)

**Comment by ernestask** [comment]
This technically comes from libreport.

I’d say this is more a fundamental design issue than a technical one, as `GtkNotebook` will ask for an allocation equal to its largest page (i.e. pages are homogeneous), so that means that some page of the wizard has a lot going on inside. Moreover, the message at the bottom only makes it worse, given that it’s added dynamically and causes the toplevel to grow. I’m no designer, but such messages should be placed in the content area, or at the very least be presented as a modal dialog.

I’m not sure which page could be acting out in this case, but throwing more scrolled windows at it might work around this.

<sup><sub>Or I’m completely wrong about it, and nothing makes sense.</sub></sup>

**Comment by abitrolly** [comment]
https://github.com/abrt/libreport/pull/539
