### ISSUE TITLE
Frequently poor notification content

### ISSUE THREAD

**Issue by smithfred** [abrt/abrt#1364]
ABRT messages are frequently indistinguishable from each other, like the top item in the below screenshot:

![abrt](https://user-images.githubusercontent.com/6663270/37211097-bfa2945e-23a2-11e8-9dad-b14ed6f4b7bd.png)

This means the user has to click the notification and open ABRT just to see what the application was (in this case, gnome-calendar).

I'm not sure if this is because of the lack of an "application name" (Zeitgeist Datahub obviously has this, in contrast), but having "gnome-calendar" in the notification text would be much more useful than the current situation.

It would also be much better to fit the full message into the collapsed notification - otherwise once the popover has disappeared, it's not possible to see the ellipsised content.

This applies to a lesser degree even with the 2nd item above - not clear at all what clicking either message does.

So for instance the following would be better:

Heading: Oops, it seems [app] crashed.
Body: To help resolve the issue, click to send a report.

The wording's a bit tricky because of the (IMO quesitonable) hiding of the action buttons in the menu, but it's clearer than at present. I'm not sure if it's possible to change the exact message in the notification menu vs. the popup?

**Comment by ernestask** [comment]
https://github.com/abrt/abrt/issues/1360#issuecomment-456713347 will provide some context on the Calendar issue.

> The wording's a bit tricky because of the (IMO quesitonable) hiding of the action buttons in the menu, but it's clearer than at present. I'm not sure if it's possible to change the exact message in the notification menu vs. the popup?

Whether questionable or not, this is a thing done by GNOME Shell, not ABRT. And, yes, it is impossible to have different wording. A notification is a notification is a notification is a notification - you set the text once and then the server is free to do whatever it wants with it.

Despite everything, I am going to close this in favor of #1360, since I feel like the goal is shared.
