### ISSUE TITLE
Finish removal of default configuration files

### ISSUE THREAD

**Issue by mgrabovsky** [abrt/abrt#1396]
In #1387, I removed most references to default config files. However, there are still some references left intertwined within the logic of `abrt-dbus`.

The problem is that `abrt-dbus` is trying to read the defaults from the, now missing, default files. The rest of ABRT relies on the defaults in [`abrt_conf.c`](https://github.com/abrt/abrt/blob/beada3e/src/lib/abrt_conf.c), which also sets the globals `g_settings_*` during initialisation.

We should hence keep all the defaults in one place in the code and allow consistent access to them, as well as to user-configured settings, via a single API used by `abrt-dbus`, as well as the rest.

**Comment by jfilak** [comment]
Who has made the decision to drop the default files? I would rather drop the /etc/abrt/conf.d files and  pushed ABRT closer the goal where /etc contains only overwrites and distros ship the default configuration in read-only files. (I should have spent more time on this topic when I was working on abrt configuration daemon, sorry.)

**Comment by ernestask** [comment]
Well, for one, default files don’t make sense, since you just have two places for system-wide configuration.

**Comment by jfilak** [comment]
Yep, I was obsessed by /etc/systemd/system and /usr/lib/systemd/system - but that's a little bit different story - but /usr/share/abrt/conf.d was the best way how to deal with the configuration on Atomic. Not sure if Atomic is still a thing.

At the time I was working on the configuration daemon, I didn't want to put all defaults into code because we always had the dream that ABRT is used by several distros and each has own plugins for which we cannot put Defaults into code.

**Comment by jfilak** [comment]
I just could not find discussion about possible solutions. 

I just wanted to learn what's is your plan, who made the decision, what are the consequences.

OUT

**Comment by xsuchy** [comment]
I made the decision. Clearly, other distributions do not pick up ABRT. So we are focusing on one distribution. Clearly having configs in two places, where sometimes both are read and sometimes only once place is read is suboptimal.

**Comment by ernestask** [comment]
I’m not quite sure what the context is as regards Atomic, but why reinvent multiple wheels when, e.g., GSettings allows vendor overrides?

**Comment by jfilak** [comment]
I didn't want to use GSettings because ABRT is installed in the minimal system and I was afraid that the dependency on GSettings would be a subject of outrages from folks responsible for that topic - I am not sure I mentioned this point in the github issues linked to abrt-config daemon. I should have been more verbose in the documentation.

**Comment by ernestask** [comment]
I’m not sure I follow. There already is a dependency on GLib and it’s not like you’re forced to use the dconf backend.

Are those claims of possible outrage based on anything? Is it only RHEL users? Even satyr takes it so seriously that it bundled a JSON parser, though I don’t know anyone who cares, because usually the first step is to just remove ABRT from their system.

**Comment by jfilak** [comment]
Clarification: I am not trying to convince you to keep two configuration files or sustain the abrt configuration daemon.

> There already is a dependency on GLib and it’s not like you’re forced to use the dconf backend.

Thanks for making it clear to me. I was under the impression that if you want to use GSettings you must just also the service - dconf, right? (By the way, I don't think ABRT is the only thing which depends on GLib on RHEL - I mean in the minimal system). 

> Are those claims of possible outrage based on anything? Is it only RHEL users? 

Yep, at least on RHEL ABRT was a part of the minimal (base) system.

>  because usually the first step is to just remove ABRT from their system.

That's correct for experienced users (10% of users, right?). RHEL customers are afraid of doing so (because Red Hat installed it and it may play a significant role ...) and RHEL POs (except CEE representatitves) wanted to keep ABRT installed (it is one of the things that other enterprise linux distros do not have) - so size matters.

That was the state of the art when I was working at Red Hat, it was long time ago. I cannot comment the current situation.

Anyways, I might have made wrong decision.

Thank you for taking my comments seriously.

**Comment by ernestask** [comment]
> Clarification: I am not trying to convince you to keep two configuration files or sustain the abrt configuration daemon.

I honestly am just trying to understand the previous mindset.

> Thanks for making it clear to me. I was under the impression that if you want to use GSettings you must just also the service - dconf, right? (By the way, I don't think ABRT is the only thing which depends on GLib on RHEL - I mean in the minimal system).

Yes, dconf is that service. In addition to it, you have the “keyfile” and “memory” backends. Of course, the latter one is not entirely useful to us, but using the former wouldn’t be too different due to it using INI-like files to store the configuration. You could argue that storing the defaults in the GSettings schema that can be modified at any time (though you might have to reset the value afterwards for it to take effect) is the same, but we could drop some of our code in exchange here with what I perceive as no downside.

dconf itself is also a sub-1M package, so I would go as far as arguing for its use. Though now I’m thinking it would be unprecedented to have a non-desktop-application project making use of it.

> That's correct for experienced users (10% of users, right?). RHEL customers are afraid of doing so (because Red Hat installed it and it may play a significant role ...) and RHEL POs (except CEE representatitves) wanted to keep ABRT installed (it is one of the things that other enterprise linux distros do not have) - so size matters.

I keep forgetting that I live in a bubble, because my data set is my friends and the Fedora users in the GNOME community, who are very much “power users”.

At the same time, we have the minimization team: https://docs.fedoraproject.org/en-US/minimization/ that might come up with something interesting in this topic.
