### ISSUE TITLE
rewrite the c/c++ hook to use systemd/journald to get the cores

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#548]
Opened '20121105T15:34:02' by jmoskovc as https://fedorahosted.org/abrt/ticket/849
- journald intercepts the C/C++ crashes using the same method as ccpp-hook (core_pattern) which can result in collision - whoever is started later wins
- the current journald API doesn't seem to provide a way to register a callback to events, so the only way to detect a new crash is to poll the journald which feels wrong - the polling is wrong and we want to react to the crash immediately
- heard rumours that Suse already uses journald to catch cores, so if we want to make abrt work on Suse we need to support this

**Comment by jfilak** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1187017

**Comment by mozeq** [comment]
Nice, took only 3 years ;)

**Comment by jfilak** [comment]
Haha and it is still not ready for production. The current implementation blindly creates an abrt dump directory for every coredump it finds. I have to spend more time on refactorization of ABRT to be able to make the implementation more sophisticated (eg. do not create dump directories for blacklisted binaries or unpackaged stuff, etc.)

**Comment by hadess** [comment]
Why does it need to copy the files? Can't it use them in place?

**Comment by jfilak** [comment]
`Why does it need to copy the files?`
Just because ABRT needs all the files in a single directory. ABRT uses direct access to those files without any abstraction and no symbolic links are allowed for security reasons. You can imagine `/var/tmp/abrt` as a database with a single table and all its subdirectories as rows in the table.

`Can't it use them in place?`
We are going to teach ABRT to be able to use data from journald without the need to copy it, but it will take us some time.

**Comment by xsuchy** [comment]
I believe this is done and we can close it.
