### ISSUE TITLE
enable pidns wrapping to support docker containers

### ISSUE THREAD

**Issue by goern** [abrt/abrt#885]
Please have a look at the pidns support used by Docker containers so that we can catch crashed applications inside of containers.

**Comment by jfilak** [comment]
Some work on this has been done, so if you want to check it out, follow these steps:
1. clone libreport git
2. git checkout rhel7_containers
3. ./autogen && ./configure && make rpm
4. install the rpms
5. clone abrt git
6. git checkout rhel7_containers
7. ./autogen && ./configure && make rpm
8. install the rpms
9. run bash in a docker and kill sleep there

I didn't build a super privileged container yet, because I'm not sure what its contents will be:
https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2015-February/msg00026.html
