### ISSUE TITLE
abrtd should be on D-Bus

### ISSUE THREAD

**Issue by hadess** [abrt/abrt#895]
I don't quite understand why abrt-dbus is separate from D-Bus. In any case, there's currently no way to detect whether abrtd is running, without polling.

abrtd should get on the bus, so we can detect whether it is running.

**Comment by jfilak** [comment]
Me neither :) Perhaps someone who has developed `abrt-dbus` had some objections about unnecessary memory consumption, reliability and a pair of some archaic points I cannot recollect, so he created a standalone, one-shot utility for querying the ABRT problem data instead of a generic D-Bus service. (Maybe D-Bus was not so sexy in 2009 (abrtd) or 2011(abrt-dbus)).

`abrtd` takes care about processing new problems.
`abrt-dbus` provides users with high level access to the detected problems.

We had no capacity to merge `abrtd` and `abrt-dbus`, there were plenty more important things to do and no one has any request to do that yet.

**Comment by hadess** [comment]
Something like that would do:
```
diff --git a/src/daemon/abrtd.c b/src/daemon/abrtd.c
index cce49eb..1158341 100644
--- a/src/daemon/abrtd.c
+++ b/src/daemon/abrtd.c
@@ -54,6 +54,7 @@ static int s_signal_pipe[2];
 static int s_signal_pipe_write = -1;
 static unsigned s_timeout;
 static bool s_exiting;
+static guint name_id = 0;
 
 static GIOChannel *channel_socket = NULL;
 static guint channel_id_socket = 0;
@@ -625,11 +626,21 @@ int main(int argc, char** argv)
     /* Only now we want signal pipe to work */
     s_signal_pipe_write = s_signal_pipe[1];
 
+    /* Own a name on D-Bus */
+    name_id = g_bus_own_name (G_BUS_TYPE_SYSTEM,
+                              "org.freedesktop.problemsXXX",
+                              G_BUS_NAME_OWNER_FLAGS_NONE,
+                              NULL, NULL, NULL,
+                              NULL, NULL);
+
     /* Enter the event loop */
     log_debug("Init complete, entering main loop");
     run_main_loop(pMainloop);
 
  cleanup:
+    if (name_id > 0)
+        g_bus_unown_name (name_id);
+
     /* Error or INT/TERM. Clean up, in reverse order.
      * Take care to not undo things we did not do.
      */
```

Any ideas for a good D-Bus name?
"org.freedesktop.problems" is already taken by abrt-dbus.

I'll send it for review once I have that name.

**Comment by jfilak** [comment]
How about "org.freedesktop.problems.daemon"?

**Comment by hadess** [comment]
Works for me.
